add analyse univarié file
Justine-league/LA-DATA-DREAM-TEAM-equipe-justine pull request #48
Opened 2022-12-12 10:37 UTC by lilifull

Valentin, dans ce commit j'ai ajouter un Jupiter notebook avec l'analyse univariée sur les features.

2022-12-14 09:28 UTC, ValBaron10 requested changes
Je ne vois que un fichier checkpoint dans ce pull request... 
Soit il manque le fichier que je dois vraiment reviewer, soit c'est une erreur ?
@lilifull vérifie que c'est bien ça que tu voulais que je regarde.

2022-12-14 16:09 UTC, lilifull commented
Oui tu as raison je n'ai pas mis le bon fichier, ça devrait être bon maintenant. Ce je j'ajoute avec ce commit c'est l'analyse univalves des données dans un fichier notebook.

2022-12-14 16:23 UTC, ValBaron10 requested changes
Il faut enlever de ton commit le fichier checkpoint. Il n'est pas utile pour les autres développeurs c'est un fichier propre à ton ordinateur. On ne commit que le code source utile aux autres développeurs. Refais un commit en l'ayant enlevé (et pense à mettre des .gitignore dans ton dossier pour être sûre de ne plus les commit).

Tu as bien étudié tes données, les graphiques que tu fais sont intéressants, mais on reste sur notre faim en ce qui concerne tes conclusions : 
- est-ce qu'on doit les supprimer les valeurs dispersées ?
- c'est quoi toutes ces valeurs qui font exactement le même poids/taille et qui ont des Nan en distance ? 
- est-ce qu'au contraire on garde toutes les valeurs parce que certes elles sont dispersées mais elles paraissent logiques ?

Là en l'état tu ne prends pas de décision, tu représentes des valeurs intéressantes mais tu n'en conclues pas assez de choses.

2022-12-14 16:29 UTC, lilifull commented
ok je vais enlever le checkpoint, merci pour l'explication c'était un peu flou pour moi. Il y a une autre tâche qui est prévu pour les outliers, c'est là que je vais les traiter mais je vais le spécifié dans ce notebook pour plus de compréhenssion.

2022-12-15 16:05 UTC, ValBaron10 approved these changes
J'accepte car on a vu qu'on ne pouvait pas supprimer les checkpoints.

2022-12-15 16:06 UTC, merged